#### INGRESS: TOPOSERVICE & SERVICE ####
servicetopo:
  port: 8181
  name: toposervice-service
serviceserver:
  port: 3000
  name: server-service
exposedServiceType: NodePort

ingress:
  enabled: false
  className: ""
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: cluster-ip
      paths:
        - path: /(.*)
          pathType: ImplementationSpecific
          backservicename: "server-service"
          backserviceport: 3000
        - path: /toposervice/(.*)
          pathType: ImplementationSpecific
          backservicename: "toposervice-service"
          backserviceport: 8181
  tls: []

#### IMAGES ####
images:
  server:
    repository: codeurjc/server
    tag: "v1.0"
    pullPolicy: IfNotPresent
  planner:
    repository: lourdesmorente/new-planner
    tag: "1.0.0"
    pullPolicy: IfNotPresent
  toposervice:
    repository: codeurjc/toposervice
    tag: "v1.0"
    pullPolicy: IfNotPresent
  weatherservice:
    repository: codeurjc/weatherservice
    tag: "v1.0"
    pullPolicy: IfNotPresent
  mongo:
    repository: mongo
    tag: "5.0.6-focal"
    pullPolicy: IfNotPresent
  mysql:
    repository: mysql
    tag: "8.0.28"
    pullPolicy: IfNotPresent
  rabbitmq:
    repository: rabbitmq
    tag: "3.9-management"
    pullPolicy: IfNotPresent

#### VOLUMES ####
persistence:
  useExistingVolumes: false
  dinamicallyCreateVolumes: false
  mysql:
    storageClass: mysql-storageclass
  mongo:
    storageClass: mongo-storageclass
  rabbitmq:
    storageClass: rabbitmq-storageclass
  defaultStorageClassName: standard

#### NETWORK POLICIES ####
useNetworkPolicies: true

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

metrics:
  enabled: false

resources:
  request:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
