---
{{- $fullName := include "eoloplants.fullname" . -}}
{{- $useExistingVolume := (.Values.persistence.useExistingVolumes) -}}
{{- $dinamicallyCreateVolume := (.Values.persistence.dinamicallyCreateVolumes) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-mysql-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $fullName }}-mysql
      {{- include "eoloplants.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullName }}-mysql
        {{- include "eoloplants.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ $fullName }}-mysql
        image: {{ .Values.images.mysql.repository }}:{{ .Values.images.mysql.tag }} 
        imagePullPolicy: {{ .Values.images.mysql.pullPolicy }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eoloplantsDB
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: {{ $fullName }}-datadb
      volumes:
      - name: {{ $fullName }}-datadb
        persistentVolumeClaim:
          claimName: {{ $fullName }}-mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $fullName }}-mysql-pvc
spec:
  {{- if $useExistingVolume }}
  storageClassName: {{ $fullName }}-{{ .Values.persistence.mysql.storageClass }}
  {{- else if $dinamicallyCreateVolume }}
  storageClassName: {{ .Values.persistence.defaultStorageClassName }}
  {{- else }}
  storageClassName: {{ $fullName }}-mysql
  {{- end }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-mysql-service
  labels:
    app: {{ $fullName }}-mysql
    {{- include "eoloplants.labels" . | nindent 4 }}
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: {{ $fullName }}-mysql-port
  selector:
    app: {{ $fullName }}-mysql
  type: ClusterIP

{{- if .Values.useNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}-mysql-from-server
spec:
  podSelector:
    matchLabels:
      app: {{ $fullName }}-mysql
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ $fullName }}-server
    ports:
    - port: 3306
      protocol: TCP
{{- end -}}
