---
{{- $fullName := include "eoloplants.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-weatherservice-deploy
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ $fullName }}-weatherservice
      {{- include "eoloplants.selectorLabels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ $fullName }}-weatherservice
        {{- include "eoloplants.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 1001
      restartPolicy: Always
      containers:
      - name: {{ $fullName }}-weatherservice
        image: {{ .Values.images.weatherservice.repository }}:{{ .Values.images.weatherservice.tag }}
        imagePullPolicy: {{ .Values.images.weatherservice.pullPolicy }}
        env:
        - name: GRPC_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: GRPC_PORT
          value: "9090"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-weatherservice-service
  labels:
    app: {{ $fullName }}-weatherservice
    {{- include "eoloplants.labels" . | nindent 4 }}
spec:
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: {{ $fullName }}-weatherservice-port
  selector:
    app: {{ $fullName }}-weatherservice
  type: ClusterIP
  
{{- if .Values.useNetworkPolicies }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $fullName }}-weather-from-planner
spec:
  podSelector:
    matchLabels:
      app: {{ $fullName }}-weatherservice
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ $fullName }}-planner
    ports:
    - port: 9090
      protocol: TCP
{{- end -}}
